### ISSUE TITLE
Hot tub water quality

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/esphome-config#1]
Capture the following sensor data:
* Temperature (Dallas)
* TDS (ADC)
* pH (ADC)

This is for a jcallaghan/home-assistant-config#12 project.

**Comment by jcallaghan** [comment]
Dallas sensor - https://esphome.io/components/sensor/dallas.html

**Comment by jcallaghan** [comment]
TDS (ADC) - https://esphome.io/components/sensor/adc.html
Sample sketch - https://www.seeedstudio.com/blog/2020/01/19/tds-in-water-what-is-tds-and-how-do-you-measure-tds-in-water/

**Comment by jcallaghan** [comment]
For the pH sensor. Same approach as #4 using ADC.
Sample sketch and calculation from volts to pH here - https://www.electroniclinic.com/ph-sensor-arduino-how-do-ph-sensors-work-application-of-ph-meter-ph-sensor-calibration/

**Comment by otakon87** [comment]
Hi @jcallaghan can you help me out? I'm trying too to integrate a tds reader in esphome, I'm not an expert and fail to import the right formula. Can you send me your code for the tds reader? This is my mail otakon87@hotmail.com. Thank you Very much
