### ISSUE TITLE
Hot tub pH sensor

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/esphome-config#6]
For the pH sensor. Same approach as #4 using ADC.
Sample sketch and calculation from volts to pH here - https://www.electroniclinic.com/ph-sensor-arduino-how-do-ph-sensors-work-application-of-ph-meter-ph-sensor-calibration/

_Originally posted by @jcallaghan in https://github.com/jcallaghan/esphome-config/issues/1#issuecomment-622507908_

**Comment by jcallaghan** [comment]
Examples
* https://www.instructables.com/id/ARDUINO-PH-METER/
* https://rootsaid.com/ph-sensor-arduino/
* https://www.electroniclinic.com/ph-sensor-arduino-how-do-ph-sensors-work-application-of-ph-meter-ph-sensor-calibration/

**Comment by jcallaghan** [comment]
Needed to add a [sliding window average](https://esphome.io/components/sensor/index.html) using a [filter](https://esphome.io/components/sensor/index.html#sensor-filters) as there were fluctuations in the data.

![image](https://user-images.githubusercontent.com/7449908/80866040-7bdeeb80-8c84-11ea-8375-9d07eedd7b73.png)

**Comment by mrand** [comment]
Neat setup!  I looked real quick and don't see it mentioned - how often does it need to be re-calibrated?

BTW, if you lower your TA, you might not have as much upwards pH drift.  My pH remains pretty stable.

**Comment by MagdalenaRyba** [comment]
> Needed to add a [sliding window average](https://esphome.io/components/sensor/index.html) using a [filter](https://esphome.io/components/sensor/index.html#sensor-filters) as there were fluctuations in the data.
> 
> ![image](https://user-images.githubusercontent.com/7449908/80866040-7bdeeb80-8c84-11ea-8375-9d07eedd7b73.png)

hello, can you share the code

**Comment by jcallaghan** [comment]
Folks, thanks for your comments and contributions. Life has been a little hectic and I've had my focus elsewhere, forgive me. Over the coming weeks I will respond to each and every one of your comments as well as bring this repo back to life. I have lots to share. 🫶🏼

<img width="410" alt="image" src="https://user-images.githubusercontent.com/7449908/181057908-918b538b-00c3-4673-a87d-1e3928bdf08d.png">
